"""Initial tables with SQLite support

Revision ID: 06cbb75ba0b8
Revises: 
Create Date: 2025-06-17 13:38:48.559378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06cbb75ba0b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('personality_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_creators_active', 'creators', ['is_active'], unique=False)
    op.create_index('idx_creators_slug', 'creators', ['slug'], unique=False)
    op.create_table('system_health',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('health_metadata', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_checked', 'system_health', ['checked_at'], unique=False)
    op.create_index('idx_health_service', 'system_health', ['service_name'], unique=False)
    op.create_index('idx_health_status', 'system_health', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('analytics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_created', 'analytics', ['created_at'], unique=False)
    op.create_index('idx_analytics_creator', 'analytics', ['creator_id'], unique=False)
    op.create_index('idx_analytics_event', 'analytics', ['event_type'], unique=False)
    op.create_index('idx_analytics_user', 'analytics', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_creator', 'conversations', ['creator_id'], unique=False)
    op.create_index('idx_conversations_updated', 'conversations', ['updated_at'], unique=False)
    op.create_index('idx_conversations_user', 'conversations', ['user_id'], unique=False)
    op.create_table('rate_limits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rate_limits_user_endpoint', 'rate_limits', ['user_id', 'endpoint'], unique=False)
    op.create_index('idx_rate_limits_window', 'rate_limits', ['window_start'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('profile_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_profiles_channel', 'user_profiles', ['channel_name'], unique=False)
    op.create_index('idx_profiles_user', 'user_profiles', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index('idx_sessions_expires', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_sessions_token', 'user_sessions', ['session_token'], unique=False)
    op.create_index('idx_sessions_user', 'user_sessions', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_messages_created', 'messages', ['created_at'], unique=False)
    op.create_index('idx_messages_role', 'messages', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_role', table_name='messages')
    op.drop_index('idx_messages_created', table_name='messages')
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_sessions_user', table_name='user_sessions')
    op.drop_index('idx_sessions_token', table_name='user_sessions')
    op.drop_index('idx_sessions_expires', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('idx_profiles_user', table_name='user_profiles')
    op.drop_index('idx_profiles_channel', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('idx_rate_limits_window', table_name='rate_limits')
    op.drop_index('idx_rate_limits_user_endpoint', table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_index('idx_conversations_user', table_name='conversations')
    op.drop_index('idx_conversations_updated', table_name='conversations')
    op.drop_index('idx_conversations_creator', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_analytics_user', table_name='analytics')
    op.drop_index('idx_analytics_event', table_name='analytics')
    op.drop_index('idx_analytics_creator', table_name='analytics')
    op.drop_index('idx_analytics_created', table_name='analytics')
    op.drop_table('analytics')
    op.drop_table('users')
    op.drop_index('idx_health_status', table_name='system_health')
    op.drop_index('idx_health_service', table_name='system_health')
    op.drop_index('idx_health_checked', table_name='system_health')
    op.drop_table('system_health')
    op.drop_index('idx_creators_slug', table_name='creators')
    op.drop_index('idx_creators_active', table_name='creators')
    op.drop_table('creators')
    # ### end Alembic commands ###
